### ISSUE TITLE
how to use this plugin? is there an example

### ISSUE THREAD

**Issue by linlinyao1** [flovilmart/cocoapods-mix-frameworks#1]
I have met the needs to mix framework and static library, and really interested in your plugin. Can you give an example to show how to use?

**Comment by flovilmart** [comment]
In your Podfile:

```
# Podfile
plugin 'cocoapods-mix-frameworks'
mix_frameworks
```

If you're using a Gemfile:

```
gem 'cocoapods-mix-frameworks'
```

or

`$ gem install cocoapods-mix-frameworks`
