### ISSUE TITLE
Swift is not supported for static libraries.

### ISSUE THREAD

**Issue by ihomam** [flovilmart/cocoapods-mix-frameworks#2]
I have a project written in Objective-c. 
I Used this plugin to include some swift pods. 
'Pod install' executed successfully, It used to expel this "target has transitive dependencies that include static binaries". but with the plugin it worked. Yay.
The problem is now the project can't be compiled, I always get "Swift is not supported for static libraries." tapping on the issue would take me to the swift pod that i just integrated.

Any idea what to do?

**Comment by flovilmart** [comment]
What version of cocoa pods are you using? also, you should probably have multiple targets:
```
target 'MyApp' do
  pod 'pod-static-lib'
done

target 'MyAppFramework' do 
  use_frameworks!
  pod 'Swift library'
done
```

Then in your project
- have an app target 'MyApp'
- have a framework target 'MyAppFramework'

Add MyAppFramework to the target dependencies.

**Comment by ihomam** [comment]
THX for the quickest response ever.
Cocoapods version is : 1.1.1
Yes, i have multiple targets. 
I need the pod to be in one of the targets. So it looks something like this

```
plugin 'cocoapods-mix-frameworks'
mix_frameworks
target 'MyApp' do
  pod 'swift library'
  pod 'objc library'
done

target 'MyAppWidget' do
  pod 'objc library'
done

target 'MyAppTestTarget' do
  pod 'objc library'
done
```

**Comment by flovilmart** [comment]
So basically you need a 'surrogate' framework target for all your swift frameworks, then use that surrogate Framework target (which can be empty by the way).

Do you have a list of the deps you're using? I could probably post an example here.

**Comment by flovilmart** [comment]
@ihomam see #3

**Comment by ihomam** [comment]
THANK you for your help. It worked smoothly.

**Comment by flovilmart** [comment]
Eheh no problem!
