### ISSUE TITLE
Help me using cocoapods-mix-frameworks

### ISSUE THREAD

**Issue by super-brian** [flovilmart/cocoapods-mix-frameworks#6]
Dear Florent Vilmart,

I have this error:
`[!] The 'Pods-WayStride' target has frameworks with conflicting names: mapbox.framework.`

it is because I already use this in my Podfile
`pod 'Steerpath', '3.3.4'`

which has mapbox.framework, but I just added this, too.
`pod 'MapboxNavigation', '~> 0.17'`

In this case, it looks like that cocoapods-mix-frameworks might help me, but I tried, but no luck.
my Podfile looks like this:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

plugin 'cocoapods-mix-frameworks'
mix_frameworks

# by SP
source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/nimbledevices/steerpath-sdk-ios-podspec.git'
source 'https://bitbucket.org/nimbledevices/steerpath-mapbox-ios-podspec.git'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#use_frameworks!

target 'WayStride' do

  # platform :ios, '8.0'

   pod 'Steerpath', '3.3.4'
   pod 'SwiftyJSON'
   pod 'Mixpanel-swift'
   pod 'Toast-Swift', '~> 3.0.1'

   pod 'Firebase/Core'
   pod 'Firebase/Messaging'
   
   pod 'MapboxNavigation', '~> 0.17'

end
```
Since README is not in detail and I am kind of newbie in this area, could you help me solve this problem?

**Comment by flovilmart** [comment]
I'm not sure this project is what you're looking for, nor that your issue can be solved using this project.

This project allows a user to use both Framework and static lib targets in the same project, leveraging a bridge framework target inside your project as the demo demonstrates.
